// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqnyJs6Hc5xLngaH7tn8Vlp4k6Dua8_0',
    appId: '1:275426029528:web:547d6329763c2a7b94ccad',
    messagingSenderId: '275426029528',
    projectId: 'shop-app-5444c',
    authDomain: 'shop-app-5444c.firebaseapp.com',
    storageBucket: 'shop-app-5444c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSCmfkexs5JHkHEMJbV8JvLPA4K3xgVU',
    appId: '1:275426029528:android:ddb3b2c7e9b3f39394ccad',
    messagingSenderId: '275426029528',
    projectId: 'shop-app-5444c',
    storageBucket: 'shop-app-5444c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH42TUaT8M_Sgtt7-L7kzP4G4iZ4CcA4c',
    appId: '1:275426029528:ios:45705bf8430e35a594ccad',
    messagingSenderId: '275426029528',
    projectId: 'shop-app-5444c',
    storageBucket: 'shop-app-5444c.appspot.com',
    iosClientId: '275426029528-691i8ks4l0kb8tjhshh07p5ptb17rc99.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
